site_name: Primeiro Projeto de Dados
site_url: https://theosplourencao.github.io/estrutura-workshop/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - social
  - mkdocstrings:
      default_handler: python

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/theosplourencao
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/theo-louren%C3%A7%C3%A3o-779b05a3/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes

copyright: |
  &copy; 2023 <a href="https://github.com/theosplourencao"  target="_blank" rel="noopener">Theo Lourenção</a>